# docker-compose.dev.yml
# Used to spin up multiple (networked) containers in the project workspace

# Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
# (Adding the "ports" property to this file will not forward from a Codespace.)

version: "3.8"

services:
  # primary container (specified in devcontainer.json)
  app:
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    init: true
    volumes:
      # mounts project root under /workspace
      - ..:/workspace:cached
      # mounts devcontainer/.vscode under root of workspace (these launch tasks are only usable within devcontainer)
      - .vscode:/workspace/.vscode:cached
      # Mount docker.sock in order to run docker from this docker dev container
      - /var/run/docker.sock:/var/run/docker.sock
      # mounts the local tls certs folder
      # - ../tls:/app/tls:cached
      # mounts the data exports folder
      # - $HOME/.exports:/workspace/.exports:cached
      # mounts the local certs folder
      # - $HOME/.certs:/app/certs:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Use a shared network to connect with other containers
    networks:
      - app-nw
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    volumes:
      - .mysql:/var/lib/mysql
    env_file: .env
    networks:
      - app-nw
    ports:
      - 127.0.0.1:3306:3306
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    env_file: .env
    volumes:
      - .redis:/var/lib/redis
    networks:
      - app-nw
    ports:
      - 127.0.0.1:6379:6379

networks:
  app-nw:
    driver: bridge
